build_run:
		docker build -t lagashmx/go-workshop:dev .
		docker run -it lagashmx/go-workshop:dev
build:
		docker build -t lagashmx/go-workshop:dev .
run:		
		docker run -it lagashmx/go-workshop:dev
gointo:
		docker run -it lagashmx/go-workshop:dev /bin/bash
test:
		docker run -it lagashmx/go-workshop:dev go test